apiVersion: v1
kind: PersistentVolume
metadata:
  name: mycache-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mycache-hostpath
  hostPath:
    path: /cache-data
    type: DirectoryOrCreate
