apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycache-pvc
  namespace: caching
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mycache-hostpath
  resources:
    requests:
      storage: 20Gi
